# Site settings
title: Solar Energy
description: A blog for project site on Solar Energy calculation module
baseurl: "/SolarEnergy/" # the subpath of your site, e.g. /blog
url: "https://rafburzy.github.io" #

# User settings
username: Solar Energy Project Site
user_description: Anon Developer at Lorem Ipsum Dolor
user_title: Python based module for PV modules calculations
#email: anon@anon.com
twitter_username: rafburzy
github_username:  rafburzy
#gplus_username:  lorem_ipsum
#disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
